### Prueba del microsevicio
GET http://127.0.0.1:8000/
Content-Type: text/html


### Listar Horario Sala
GET http://127.0.0.1:8000/api/horarios_salas
Content-Type: application/json
### Listar ingreso
GET http://127.0.0.1:8000/api/ingresos
Content-Type: application/json
### Listar programa
GET http://127.0.0.1:8000/api/programas
Content-Type: application/json


### Consultar un Horario Sala
GET http://127.0.0.1:8000/api/horarios_salas/3
Content-Type: application/json
### Consultar un ingreso
GET http://127.0.0.1:8000/api/ingresos/3
Content-Type: application/json
### Consultar un programa
GET http://127.0.0.1:8000/api/programas/3
Content-Type: application/json


### Registrar un Horario Sala
POST http://127.0.0.1:8000/api/horarios_salas
Content-Type: application/json
{
   "dia": "Viernes",
   "materia": "Programación",
   "horaInicio": "13:30",
    "horaFin": "16:40",
     "idPrograma": "1",
     "idPrograma": "1"
}
### Registrar un ingreso
POST http://127.0.0.1:8000/api/ingresos
Content-Type: application/json
{
   "codigoEstudiante": "555555",
   "nombreEstudiante": "Johan",
   "idPrograma ": "1",
   "fechaIngreso": "20/5/24",
   "horaIngreso ": "14:20",
   "horaSalida ": "15:10",
   "idResponsable  ": "1",
   "idSala": "1",
   "created_at": "",
   "updated_at": ""
}
### Registrar un programa
POST http://127.0.0.1:8000/api/programas
Content-Type: application/json
{
   "nombre": "Lenina"
}


### Actualizar datos de un Horario Sala
PUT http://127.0.0.1:8000/api/horarios_salas/3
Content-Type: application/json
{
   "dia": "Lunes",
   "materia": "Cálculo",
   "horaInicio": "12:10",
   "horaFin": "15:00",
   "idPrograma": "1",
   "idSala": "1",
}
### Actualizar datos de un ingreso
PUT http://127.0.0.1:8000/api/ingresos/3
Content-Type: application/json
{
   "codigoEstudiante": "66666",
   "nombreEstudiante": "Nina",
   "idPrograma ": "2",
   "fechaIngreso": "20/7/24",
   "horaIngreso ": "14:20",
   "horaSalida ": "16:10",
   "idResponsable  ": "1",
   "idSala": "1",
   "created_at": "",
   "updated_at": ""
}
### Actualizar datos de un programa
PUT http://127.0.0.1:8000/api/programas/3
Content-Type: application/json
{
   "nombre": "Ana"
}


### Eliminar un Horario Sala
DELETE http://127.0.0.1:8000/api/horarios_salas/2
### Eliminar un ingreso
DELETE http://127.0.0.1:8000/api/ingresos/2
### Eliminar un programa
DELETE http://127.0.0.1:8000/api/programas/2
