### Prueba del microsevicio
GET http://127.0.0.1:3000/
Content-Type: text/html

#-------------------------LISTAR--------------------------#
### Listar Horario Sala
GET http://127.0.0.1:3000/api/horarios_salas
Content-Type: application/json

### Listar ingreso
GET http://127.0.0.1:3000/api/ingresos
Content-Type: application/json

### Listar programa
GET http://127.0.0.1:3000/api/programas
Content-Type: application/json

### Listar Responsable
GET http://127.0.0.1:3000/api/responsables
Content-Type: application/json

### Listar Sala
GET http://127.0.0.1:3000/api/salas
Content-Type: application/json


#------------------------CONSULTAR---------------------------#
### Consultar un Horario Sala
GET http://127.0.0.1:3000/api/horarios_salas/1
Content-Type: application/json

### Consultar un ingreso
GET http://127.0.0.1:3000/api/ingresos/1
Content-Type: application/json

### Consultar un programa
GET http://127.0.0.1:3000/api/programas/1
Content-Type: application/json

### Consultar un Responsable
GET http://127.0.0.1:3000/api/responsables/2
Content-Type: application/json

### Consultar una sala
GET http://127.0.0.1:3000/api/salas/1
Content-Type: application/json


#------------------------REGISTRAR--------------------------#
### Registrar un Horario Sala
POST http://127.0.0.1:3000/api/horarios_salas
Content-Type: application/json

{
   "dia": "Viernes",
   "materia": "Programación",
   "horaInicio": "13:30",
   "horaFin": "16:40",
   "idPrograma": "1",
   "idSala": "1"
}
### Registrar un ingreso
POST http://127.0.0.1:3000/api/ingresos
Content-Type: application/json

{
   "codigoEstudiante": "885223",
   "nombreEstudiante": "Johan Liebert",
   "idPrograma": "1",
   "fechaIngreso": "2024-06-04",
   "horaIngreso": "3:20",
   "horaSalida":"5:33",
   "idResponsable": "1",
   "idSala": "1"
}

### Registrar un programa
POST http://127.0.0.1:3000/api/programas
Content-Type: application/json

{
   "nombre": "Bases de Datos"
}

### Registrar un responsable
POST http://127.0.0.1:3000/api/responsables
Content-Type: application/json

{
   "nombre": "Daniel"
   
}

### Registrar una Sala
POST http://127.0.0.1:3000/api/salas
Content-Type: application/json

{
   "nombre": "432K"
}


#--------------------------ACTUALIZAR------------------------#
### Actualizar datos de un Horario Sala
PUT http://127.0.0.1:3000/api/horarios_salas/1
Content-Type: application/json

{
   "dia": "Martes",
   "materia": "Calculo",
   "horaInicio": "12:10",
   "horaFin": "15:00",
   "idPrograma": "1",
   "idSala": "3"
}

### Actualizar datos de un ingreso
PUT http://127.0.0.1:3000/api/ingresos/1
Content-Type: application/json

{
   "codigoEstudiante": "66666",
   "nombreEstudiante": "Nina",
   "idPrograma": "3",
   "fechaIngreso": "24-07-24",
   "horaIngreso": "14:20",
   "horaSalida": null,
   "idResponsable": "1",
   "idSala": "1"
}
### Actualizar datos de un programa
PUT http://127.0.0.1:3000/api/programas/2
Content-Type: application/json

{
   "nombre": "Arquitectura"
}

### Actualizar datos de un responsable
PUT http://127.0.0.1:3000/api/responsables/3
Content-Type: application/json

{
   "nombre": "Felipe"
}

### Actualizar datos de una sala
PUT http://127.0.0.1:3000/api/salas/3
Content-Type: application/json

{
   "nombre": "401G"
}


#--------------------------ELIMINAR-------------------------#
### Eliminar un Horario Sala
DELETE http://127.0.0.1:3000/api/horarios_salas/1
### Eliminar un ingreso
DELETE http://127.0.0.1:3000/api/ingresos/1
### Eliminar un programa
DELETE http://127.0.0.1:3000/api/programas/5
### Eliminar un responsable
DELETE http://127.0.0.1:3000/api/responsables/5
### Eliminar un Sala
DELETE http://127.0.0.1:3000/api/salas/7
